language: rust

cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

matrix:
  include:
    - env: GEO_TYPES_FEATURES=""
    - env: GEO_TYPES_FEATURES="--features serde"
    - env: GEO_TYPES_FEATURES="--features rstar"
    - env: GEO_FEATURES=""
    - env: GEO_FEATURES="--features postgis-integration"
    - env: GEO_FEATURES="--features use-proj"
    - env: GEO_FEATURES="--features use-serde"

before_cache:
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo install cargo-tarpaulin -f;
    fi

before_install:
  - if [ "${GEO_FEATURES}" == "--features use-proj" ]; then
        sudo apt-get update;
        wget https://github.com/OSGeo/proj.4/releases/download/6.2.1/proj-6.2.1.tar.gz;
        tar -xzvf proj-6.2.1.tar.gz;
        pushd proj-6.2.1 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi

script:
  - (cd geo-types && cargo build --release $GEO_TYPES_FEATURES && cargo test --release $GEO_TYPES_FEATURES)
  - (cd geo && cargo build --release $GEO_FEATURES && cargo test --release $GEO_FEATURES)

after_success:
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
