[package]
name = "wkt"
description = "Rust read/write support for well-known text (WKT)"
version = "0.1.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-wkt"

[dependencies]
geo-types = {version = "0.1.1", optional = true}

[features]
default = ["geo-types"]
