[package]

name = "wkt"
description = "Rust read/write support for well-known text (WKT)"
version = "0.0.3"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
repository = "https://github.com/georust/rust-wkt"


[dependencies]

geo = "0.0.3"
