[package]
name = "geo"
description = "Geospatial primitives and algorithms"
version = "0.8.2"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geo"
documentation = "https://docs.rs/geo/"
readme = "README.md"
keywords = ["gis", "geo", "geography", "geospatial"]

[badges]
travis-ci = { repository = "georust/rust-geo" }

[dependencies]
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
spade = "1.3.0"
failure = "0.1.1"
postgis = { version = "0.5", optional = true }
proj-sys = { version = "0.6.1", optional = true }
libc = { version = "0.2.39", optional = true }

[features]
default = []
postgis-integration = ["postgis"]
proj = ["proj-sys", "libc"]

[dev-dependencies]
approx = "0.1.1"

[package.metadata.docs.rs]
features = ["postgis"]
