[package]

name = "geo"
description = "Geospatial primitives and algorithms"
version = "0.4.3"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geo"
documentation = "https://georust.github.io/rust-geo/"
keywords = ["gis", "geo", "geography", "geospatial"]

[dependencies]
num-traits = "0.1"
serde = "0.9"
serde_derive = "0.9"

[dev-dependencies]
approx = "0.1.1"
