[package]
name = "wkt"
description = "Rust read/write support for well-known text (WKT)"
version = "0.6.0"
authors = ["Corey Farwell <coreyf@rwell.org>", "Antoine Desbordes <antoine.desbordes@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/wkt"
autobenches = true
readme = "README.md"
keywords = ["geo", "geospatial", "wkt"]

[dependencies]
geo-types = {version = "0.5", optional = true}
num-traits = "0.2"

[dev-dependencies]
criterion = { version = "0.2" }

[features]
default = ["geo-types"]

[[bench]]
name = "parse"
harness = false
